language: go
go:
- master
env:
- GOPATH=/debiantest
script: 
- go run -v ./...
- go build -v ./...
- tar -xvf knapp-deb.tar
- cp ./debiantest ./knapp-0.0.1/tree/knapp
- cp ./debiantest ./knapp-0.0.1/tree/knapp-watcher
- cd ./knapp-0.0.1
- sudo apt-get install devscripts build-essential lintian
- debuild
- cd ..
- ls
